[package]
name = "deploy_scarab_sign"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"
sncast_std = "0.35.1"

[[target.starknet-contract]]
build-external-contracts = [
    "map::ScarabSign"
]
